### ISSUE TITLE
Bug in download_dataset function: Incorrect key for file download URL

### ISSUE THREAD

**Issue by maxwass** [Waller-Lab/BSCCM#4]
The function raises a KeyError because the expected key 'stash:file-download' is not found in the response from the Dryad API. It seems that the key for the download URL has changed.

#### Description

I encountered an issue when using the `download_dataset` function in the `bsccm` package. The function raises a `KeyError` because the expected key `'stash:file-download'` is not found in the response from the Dryad API. It seems that the key for the download URL has changed.

See relevant code here: https://github.com/Waller-Lab/BSCCM/blob/806267eba1026e89df420c73a4cf7a6de5179199/bsccm/bsccm.py#L101

#### Steps to Reproduce

1. Use the following code snippet to attempt downloading the dataset:
```python
   from bsccm import download_dataset
   dataset_path = download_dataset('/path/to/bsccm/data', tiny=True)
   print('Downloaded dataset to ' + dataset_path)
```

#### Error Log
```
Downloading...metadata 220...
Total Download Progress:   0%|                                                                                     | 0.00/490M [00:00<?, ?B/s]
Traceback (most recent call last):
  File "'/path/to/bsccm/main.py", line 4, in <module>
    dataset_path = download_dataset(path, tiny=True)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/bsccm/bsccm.py", line 101, in download_dataset
    download_url = 'https://datadryad.org' + file_info['_links']['stash:file-download']['href']
KeyError: 'stash:file-download'
```

#### Proposed Solution
The correct key for the download URL appears to be 'stash:download' instead of 'stash:file-download'. The code should be updated to:

```
download_url = 'https://datadryad.org' + file_info['_links']['stash:download']['href']
```

After doing so I can successfully download the data.

Thanks for you work on this cool project, hope this helps others.

**Comment by henrypinkard** [comment]
Thanks so much for reporting this! I just pushed a new version with your fix.
