### ISSUE TITLE
`quasi_dome_design.json` missing from python package

### ISSUE THREAD

**Issue by BenjaminDev** [Waller-Lab/BSCCM#5]
Thanks for this very well put together dataset. There is a slight break in the packaging of `bsccm` as `quasi_dome_design.json` is missing.

Reproduction:
Install in a fresh `venv` 
```
Python 3.12.2 (main, Feb 25 2024, 04:38:01) [Clang 17.0.6 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from bsccm.led_array_calibration import  get_led_na
>>> get_led_na(2)
```
Error:
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/scrtach/.venv/lib/python3.12/site-packages/bsccm/quasi_dome_design.json'
```
File is missing.

Fix:
REF: https://setuptools.pypa.io/en/latest/userguide/datafiles.html There are various ways to do this see docs.
(I can make a PR if you prefer but it's a small fix and might be simpler if I just leave it here)
```
# setup.py
...
      packages=setuptools.find_packages(),
+    package_data={"bsccm": ["*.json"]},
      install_requires=[ ...]
...
```

Test:
run:
 `./package && python -m pip install ../dist/*.whl` (In a fresh venv)

```
>>> get_led_na_xy(2)
array([-0.06211088,  0.        ])
```
and json file is present.
```
benjamin@loki /t/scrtach (main)> ls .venv/lib/python3.12/site-packages/bsccm/
bsccm.py                  led_array_calibration.py  quasi_dome_design.json <<<<<<<< File packaged in the wheel
fluorescence_processing/  phase/                    _version.py
__init__.py               __pycache__/
```

This will make the pypi install have all files included.

**Comment by henrypinkard** [comment]
Should be fixed now. Thanks for the detailed instructions!
